// Auto-generated from Revisiting Reflection xlsx · dataset sheet
// Curated for signal: YES patterns + NO patterns only, neutrals dropped.

export type NodeState = 'yes' | 'no' | 'neutral';

export interface ReflNode {
  id: string;
  state: NodeState;
  count: number;
}

export interface ReflEdge {
  from: string;
  to: string;
  n: number;
}

// Medium layer — where each instance was published. App = shipped product,
// Paper = research publication. Neither is YES or NO for Nara; it's the
// landscape dimension. Nara is a shipped device inspired by paper-only
// resources, so the App→YES path is deliberately thin.
export const mediums: ReflNode[] = [
  { id: "App", state: "neutral", count: 266 },
  { id: "Paper", state: "neutral", count: 279 },
];

export const mediumEdges: ReflEdge[] = [
  { from: "App", to: "Conversations with technology", n: 17 },
  { from: "App", to: "Future", n: 4 },
  { from: "App", to: "Past", n: 109 },
  { from: "App", to: "Reframing", n: 17 },
  { from: "App", to: "Slowness", n: 119 },
  { from: "Paper", to: "Absolute reference", n: 17 },
  { from: "Paper", to: "Ambiguity", n: 26 },
  { from: "Paper", to: "Conversations with others", n: 43 },
  { from: "Paper", to: "Conversations with technology", n: 10 },
  { from: "Paper", to: "Future", n: 5 },
  { from: "Paper", to: "Memories", n: 29 },
  { from: "Paper", to: "Past", n: 48 },
  { from: "Paper", to: "Provocation", n: 8 },
  { from: "Paper", to: "Reframing", n: 45 },
  { from: "Paper", to: "Slowness", n: 24 },
  { from: "Paper", to: "Social reference", n: 19 },
  { from: "Paper", to: "Storytelling", n: 5 },
];

export const resources: ReflNode[] = [
  { id: "Past", state: "yes", count: 120 },
  { id: "Slowness", state: "yes", count: 100 },
  { id: "Reframing", state: "yes", count: 34 },
  { id: "Conversations with others", state: "yes", count: 27 },
  { id: "Conversations with technology", state: "yes", count: 16 },
  { id: "Ambiguity", state: "yes", count: 24 },
  { id: "Storytelling", state: "yes", count: 3 },
  { id: "Absolute reference", state: "yes", count: 14 },
  { id: "Social reference", state: "yes", count: 16 },
  { id: "Provocation", state: "yes", count: 3 },
  { id: "Memories", state: "yes", count: 15 },
  { id: "Future", state: "yes", count: 6 },
];

export const patterns: ReflNode[] = [
  { id: "Social sharing", state: "yes", count: 22 },
  { id: "Abstract representation", state: "yes", count: 10 },
  { id: "Automated data collection", state: "yes", count: 8 },
  { id: "Triggering memories", state: "yes", count: 7 },
  { id: "Tangibles", state: "yes", count: 7 },
  { id: "Ambient display", state: "yes", count: 6 },
  { id: "Sensor collecting personal data", state: "yes", count: 3 },
  { id: "Tracking", state: "no", count: 41 },
  { id: "Statistics", state: "no", count: 36 },
  { id: "Journaling", state: "no", count: 35 },
  { id: "Visualization", state: "no", count: 33 },
  { id: "Prompts / guided questions", state: "no", count: 25 },
  { id: "Goal setting", state: "no", count: 23 },
  { id: "Manual tracking", state: "no", count: 21 },
  { id: "Calendar", state: "no", count: 16 },
  { id: "Text entry (non guided)", state: "no", count: 13 },
  { id: "User fills in a form", state: "no", count: 11 },
  { id: "Badges", state: "no", count: 10 },
  { id: "Chatbot", state: "no", count: 8 },
  { id: "Comparing to others", state: "no", count: 7 },
  { id: "Task list", state: "no", count: 7 },
  { id: "Comparing to a norm", state: "no", count: 5 },
  { id: "Public display", state: "no", count: 5 },
  { id: "Personality test", state: "no", count: 5 },
  { id: "Rating", state: "no", count: 5 },
  { id: "Year in pixels", state: "no", count: 4 },
  { id: "Conversational agent", state: "no", count: 2 },
  { id: "Narrative", state: "no", count: 2 },
  { id: "Leaderboard", state: "no", count: 1 },
];

export const edges: ReflEdge[] = [
  { from: "Past", to: "Tracking", n: 18 },
  { from: "Slowness", to: "Tracking", n: 18 },
  { from: "Past", to: "Statistics", n: 17 },
  { from: "Slowness", to: "Journaling", n: 17 },
  { from: "Past", to: "Journaling", n: 15 },
  { from: "Slowness", to: "Prompts / guided questions", n: 13 },
  { from: "Slowness", to: "Statistics", n: 11 },
  { from: "Past", to: "Goal setting", n: 10 },
  { from: "Past", to: "Prompts / guided questions", n: 9 },
  { from: "Slowness", to: "Goal setting", n: 9 },
  { from: "Past", to: "Manual tracking", n: 7 },
  { from: "Conversations with others", to: "Social sharing", n: 7 },
  { from: "Past", to: "Calendar", n: 7 },
  { from: "Slowness", to: "Calendar", n: 7 },
  { from: "Reframing", to: "Visualization", n: 6 },
  { from: "Past", to: "Visualization", n: 6 },
  { from: "Ambiguity", to: "Visualization", n: 5 },
  { from: "Ambiguity", to: "Abstract representation", n: 5 },
  { from: "Conversations with technology", to: "Chatbot", n: 5 },
  { from: "Past", to: "Text entry (non guided)", n: 4 },
  { from: "Absolute reference", to: "Visualization", n: 4 },
  { from: "Conversations with others", to: "Visualization", n: 4 },
  { from: "Memories", to: "Triggering memories", n: 4 },
  { from: "Social reference", to: "Manual tracking", n: 4 },
  { from: "Reframing", to: "Manual tracking", n: 4 },
  { from: "Past", to: "Badges", n: 4 },
  { from: "Slowness", to: "Badges", n: 4 },
  { from: "Slowness", to: "Task list", n: 4 },
  { from: "Reframing", to: "User fills in a form", n: 3 },
  { from: "Past", to: "Social sharing", n: 3 },
  { from: "Conversations with others", to: "Public display", n: 3 },
  { from: "Ambiguity", to: "Ambient display", n: 3 },
  { from: "Social reference", to: "Social sharing", n: 3 },
  { from: "Ambiguity", to: "Tangibles", n: 3 },
  { from: "Social reference", to: "Visualization", n: 3 },
  { from: "Reframing", to: "Goal setting", n: 3 },
  { from: "Past", to: "Task list", n: 3 },
  { from: "Reframing", to: "Journaling", n: 3 },
  { from: "Past", to: "Rating", n: 2 },
  { from: "Past", to: "Comparing to others", n: 2 },
  { from: "Absolute reference", to: "Comparing to a norm", n: 2 },
  { from: "Memories", to: "Manual tracking", n: 2 },
  { from: "Memories", to: "Text entry (non guided)", n: 2 },
  { from: "Memories", to: "Rating", n: 2 },
  { from: "Conversations with others", to: "Comparing to others", n: 2 },
  { from: "Absolute reference", to: "User fills in a form", n: 2 },
  { from: "Conversations with others", to: "Text entry (non guided)", n: 2 },
  { from: "Slowness", to: "Social sharing", n: 2 },
  { from: "Conversations with technology", to: "Conversational agent", n: 2 },
  { from: "Ambiguity", to: "Automated data collection", n: 2 },
  { from: "Past", to: "Ambient display", n: 2 },
  { from: "Past", to: "Comparing to a norm", n: 2 },
  { from: "Reframing", to: "Social sharing", n: 2 },
  { from: "Past", to: "User fills in a form", n: 2 },
  { from: "Social reference", to: "User fills in a form", n: 2 },
  { from: "Social reference", to: "Statistics", n: 2 },
  { from: "Memories", to: "Visualization", n: 2 },
  { from: "Slowness", to: "Visualization", n: 2 },
  { from: "Slowness", to: "Manual tracking", n: 2 },
  { from: "Reframing", to: "Automated data collection", n: 2 },
  { from: "Past", to: "Year in pixels", n: 2 },
  { from: "Slowness", to: "Year in pixels", n: 2 },
  { from: "Past", to: "Personality test", n: 2 },
  { from: "Slowness", to: "Personality test", n: 2 },
  { from: "Reframing", to: "Tracking", n: 2 },
  { from: "Reframing", to: "Statistics", n: 2 },
  { from: "Conversations with technology", to: "Prompts / guided questions", n: 2 },
  { from: "Conversations with technology", to: "Tracking", n: 2 },
  { from: "Conversations with technology", to: "Statistics", n: 2 },
  { from: "Slowness", to: "Chatbot", n: 2 },
  { from: "Conversations with others", to: "Leaderboard", n: 1 },
  { from: "Conversations with others", to: "Automated data collection", n: 1 },
  { from: "Reframing", to: "Text entry (non guided)", n: 1 },
  { from: "Provocation", to: "Visualization", n: 1 },
  { from: "Provocation", to: "Abstract representation", n: 1 },
  { from: "Conversations with others", to: "User fills in a form", n: 1 },
  { from: "Absolute reference", to: "Social sharing", n: 1 },
  { from: "Absolute reference", to: "Public display", n: 1 },
  { from: "Absolute reference", to: "Comparing to others", n: 1 },
  { from: "Slowness", to: "Text entry (non guided)", n: 1 },
  { from: "Ambiguity", to: "Sensor collecting personal data", n: 1 },
  { from: "Ambiguity", to: "Triggering memories", n: 1 },
  { from: "Past", to: "Automated data collection", n: 1 },
  { from: "Absolute reference", to: "Ambient display", n: 1 },
  { from: "Absolute reference", to: "Statistics", n: 1 },
  { from: "Absolute reference", to: "Automated data collection", n: 1 },
  { from: "Future", to: "Text entry (non guided)", n: 1 },
  { from: "Future", to: "Social sharing", n: 1 },
  { from: "Future", to: "Triggering memories", n: 1 },
  { from: "Memories", to: "Social sharing", n: 1 },
  { from: "Reframing", to: "Sensor collecting personal data", n: 1 },
  { from: "Conversations with others", to: "Sensor collecting personal data", n: 1 },
  { from: "Social reference", to: "Text entry (non guided)", n: 1 },
  { from: "Ambiguity", to: "Social sharing", n: 1 },
  { from: "Ambiguity", to: "Public display", n: 1 },
  { from: "Conversations with others", to: "Abstract representation", n: 1 },
  { from: "Conversations with others", to: "Tangibles", n: 1 },
  { from: "Slowness", to: "User fills in a form", n: 1 },
  { from: "Slowness", to: "Comparing to others", n: 1 },
  { from: "Social reference", to: "Comparing to others", n: 1 },
  { from: "Conversations with others", to: "Rating", n: 1 },
  { from: "Conversations with others", to: "Manual tracking", n: 1 },
  { from: "Conversations with others", to: "Statistics", n: 1 },
  { from: "Storytelling", to: "Social sharing", n: 1 },
  { from: "Storytelling", to: "Narrative", n: 1 },
  { from: "Storytelling", to: "Tangibles", n: 1 },
  { from: "Reframing", to: "Comparing to a norm", n: 1 },
  { from: "Reframing", to: "Triggering memories", n: 1 },
  { from: "Reframing", to: "Abstract representation", n: 1 },
  { from: "Slowness", to: "Abstract representation", n: 1 },
  { from: "Memories", to: "Tangibles", n: 1 },
  { from: "Slowness", to: "Tangibles", n: 1 },
  { from: "Memories", to: "Automated data collection", n: 1 },
  { from: "Past", to: "Abstract representation", n: 1 },
  { from: "Ambiguity", to: "Manual tracking", n: 1 },
  { from: "Ambiguity", to: "Text entry (non guided)", n: 1 },
  { from: "Provocation", to: "Narrative", n: 1 },
  { from: "Reframing", to: "Prompts / guided questions", n: 1 },
  { from: "Reframing", to: "Badges", n: 1 },
  { from: "Conversations with technology", to: "Badges", n: 1 },
  { from: "Conversations with technology", to: "Calendar", n: 1 },
  { from: "Conversations with technology", to: "Personality test", n: 1 },
  { from: "Past", to: "Chatbot", n: 1 },
  { from: "Future", to: "Goal setting", n: 1 },
  { from: "Future", to: "Tracking", n: 1 },
  { from: "Future", to: "Calendar", n: 1 },
];
