/* Node info data — explanations, inputs, outputs, processing for each pipeline node */

export interface NodeInfo {
  title: string;
  explanation: string;
  inputs: string[];
  outputs: string[];
  processing: string;
}

export const NODE_INFO: Record<string, NodeInfo> = {
  mic: {
    title: "INMP441 Microphone",
    explanation: "An always-on MEMS microphone that captures full environment audio. It listens to everything around the wearer — conversations, ambient sounds, background noise.",
    inputs: ["Raw sound waves from the environment"],
    outputs: ["16-bit PCM audio stream via I2S bus to ESP32"],
    processing: "Converts acoustic pressure waves into a digital audio signal at 16kHz sample rate. Consumes only 1.4mW. Runs continuously — there is no off switch (a hardwired LED indicates when it's active).",
  },
  vad: {
    title: "ESP-SR Voice Activity Detection",
    explanation: "A local neural network on Core 0 of the ESP32 that listens to the audio and decides: is someone speaking right now? This is the power gatekeeper — WiFi only turns on when speech is detected.",
    inputs: ["Raw PCM audio from PSRAM ring buffer"],
    outputs: ["Speech/silence decision", "WiFi power-on trigger when speech starts"],
    processing: "Runs an energy-based pre-filter (<0.5ms) to reject obvious silence, then ESP-SR WakeNet neural model for accurate speech detection. When speech starts, signals the WiFi radio to power on. Keeps WiFi alive for 2s after speech ends to catch pauses.",
  },
  opus: {
    title: "Opus Encoder",
    explanation: "Compresses the raw audio into a much smaller stream before sending it to the cloud. Without this, streaming would use 15x more bandwidth.",
    inputs: ["Raw PCM audio from the ring buffer (only when VAD says speech is active)"],
    outputs: ["Opus-compressed audio frames at 16kbps to WiFi streamer"],
    processing: "Encodes 20ms audio frames using the Opus codec on Core 1. Reduces 256kbps raw audio down to ~16kbps — a 16x compression. Runs in real-time with no perceptible delay.",
  },
  imu: {
    title: "6DoF IMU (GY-521 MPU-6050)",
    explanation: "A motion sensor with accelerometer + gyroscope that tracks the wearer's physical state — walking, sitting, fidgeting, lying down.",
    inputs: ["Physical acceleration and rotation from the wearer's body"],
    outputs: ["Processed motion state classification to Tier 1"],
    processing: "The ESP32 communicates with the MPU-6050 over I2C (SCL: 39, SDA: 38) at 25Hz and classifies the raw accelerometer/gyroscope vectors into motion states: walking, sitting, fidgeting, lying down, and transitions between them. Draws ~3.5mA.",
  },
  btn: {
    title: "Physical Button",
    explanation: "The only way the wearer actively interacts with Maddi. One press means: 'I have a question — listen to what I say next and give me advice.'",
    inputs: ["Physical button press from the wearer"],
    outputs: ["Activates microphone for query capture", "Triggers consultation flow", "Writes consultation flag to Tier 1"],
    processing: "A hardware interrupt fires on press. This does three things: (1) signals the mic to start capturing the spoken query, (2) kicks off the consultation pipeline in the cloud, and (3) marks this moment in Tier 1 with an elevated weight so compressors know this was an important moment.",
  },
  t1: {
    title: "Tier 1: Processed Signals",
    explanation: "The first layer of Maddi's memory. Stores the last hour of everything that's been understood from the audio — what was said, how people felt, where the wearer was, who was talking.",
    inputs: ["Transcripts, keywords, topics, speaker labels from cloud STT pipeline", "Emotional scores from Tonal Analyzer", "Scene classification from Environment Classifier", "Motion state from IMU", "Consultation flags from Button", "Social context from other Maddi devices"],
    outputs: ["Sent to Hourly Compressor every hour", "Sent to Context Assembler during consultation"],
    processing: "Stored as Protocol Buffer files on flash. Each signal type has a timestamp. After hourly compression, the raw signals are deleted to save space. During consultation, current signals are sent to the Context Assembler so the LLM has real-time context.",
  },
  t2: {
    title: "Tier 2: Daily Digest",
    explanation: "A summary of the day so far, built from hourly summaries. Captures the arc of the day — what topics dominated, how emotions shifted, key moments.",
    inputs: ["Hourly summaries from the Hourly Compressor"],
    outputs: ["Sent to Daily Compressor every 24 hours", "Sent to Context Assembler during consultation"],
    processing: "Accumulates up to 24 hourly summaries. Each summary contains dominant topics, emotional arc, key moments, environment profile, speaker interaction map, and motion patterns. After daily compression, the hourly summaries are deleted.",
  },
  t3: {
    title: "Tier 3: Weekly Digest",
    explanation: "A week-level view that reveals patterns you can't see in a single day — recurring topics, emotional trends, shifting relationships, decision habits.",
    inputs: ["Daily digests from the Daily Compressor"],
    outputs: ["Sent to Weekly Compressor every 7 days", "Sent to Context Assembler during consultation"],
    processing: "Accumulates 7 daily digests. Captures week-level emotional patterns, recurring topics, relational shifts, decision trends, and environment-mood correlations. After weekly compression, the daily digests are deleted.",
  },
  t4: {
    title: "Tier 4: Long-Term Themes",
    explanation: "Maddi's deep memory — the patterns of who you are over months and years. Stress triggers, key relationships, decision habits, places that affect your mood. This is what makes Maddi's advice personal.",
    inputs: ["Updated themes from Theme Merger (weekly)", "Updated vector embeddings from E5-small-v2"],
    outputs: ["Existing themes sent to Theme Merger for updates", "Theme embeddings sent to Semantic Search during consultation", "Encrypted storage keys linked to Crypto-Shredding"],
    processing: "Stored permanently on encrypted flash (AES-256-GCM, eFuse-protected key). Contains four sub-models: Emotional Patterns (stress triggers, mood cycles), Relational Patterns (key people, social dynamics), Decision Patterns (uncertainty types, reasoning habits), and Theme Embeddings (384-dim vectors for semantic search). Uses a 2-year rolling window with time-decay — old patterns gradually fade unless reinforced.",
  },
  eink: {
    title: "E-Ink Display (296×128)",
    explanation: "Maddi's output surface. A 200×200 binary E-Ink display that shows consultation responses as a scrollable sequence: 3 glyphs (one at a time, full-screen) followed by a single word, navigated by the potentiometer. Each glyph fills the entire screen — the wearer turns the dial to advance through the narrative arc. The display holds the last consultation between queries at zero power cost.",
    inputs: ["Validated 3 glyphs + word from Rule Constraint Layer", "Scroll position from potentiometer (5 zones)"],
    outputs: ["Visual display of glyphs and word to the wearer"],
    processing: "Connected via SPI (CS:10, DIN:11, CLK:12, DC:13, RST:14, BUSY:9). Potentiometer ADC (GPIO 8) is software-thresholded into 5 zones with ±50 hysteresis: zones 0-2 show glyphs 1-3 (full screen 200×200 bitmaps), zone 3 shows the word (centered, large type), zone 4 shows last query text. E-Ink refreshes only on zone change — 8mA per refresh, zero power to hold. Idle state: scrollable view of last consultation.",
  },
  ble: {
    title: "BLE Radio",
    explanation: "The Bluetooth radio handles two jobs: WiFi provisioning from the companion app, and social context exchange with nearby Maddi devices.",
    inputs: ["Encrypted WiFi credentials from Companion App", "Encrypted social context packets from other Maddi devices"],
    outputs: ["WiFi credentials to credential store", "Social context to External Context Buffer"],
    processing: "Uses the ESP32's shared 2.4GHz radio (time-sliced with WiFi). BLE advertising runs in WiFi-off gaps. For provisioning: SRP6a/X25519 key agreement. For social exchange: receives Ed25519-signed packets, verifies against stored public keys, drops unknown senders.",
  },
  nats: {
    title: "NATS JetStream",
    explanation: "The cloud-side message broker that receives the single audio stream from the device and fans it out to three parallel analyzers. This is why the device only needs to send one stream instead of three.",
    inputs: ["Single Opus-compressed audio stream from device via WebSocket"],
    outputs: ["Audio frames to STT Engine", "Audio frames to Tonal Analyzer", "Audio frames to Environment Classifier"],
    processing: "Receives audio frames over TLS 1.3, buffers up to 90 seconds per device (handles brief consumer hiccups), and publishes to 3 consumer groups simultaneously. Zero additional device bandwidth cost.",
  },
  stt: {
    title: "STT Engine (Deepgram)",
    explanation: "Converts spoken audio into text. This is the foundation of Maddi's understanding — everything downstream depends on accurate transcription.",
    inputs: ["Opus audio frames from NATS JetStream"],
    outputs: ["Full transcript text to Keyword Extractor", "Transcript + audio features to Speaker Identifier", "Transcript + timestamps to Aggregator"],
    processing: "Uses Deepgram's cloud STT API for real-time transcription with ~800ms latency. Produces timestamped transcript segments. During consultation, also transcribes the user's spoken query.",
  },
  tonal: {
    title: "Tonal & Emotional Analyzer",
    explanation: "Analyzes how things are said, not what is said. Detects stress, emotional arousal, sentiment shifts — the feelings behind the words.",
    inputs: ["Raw audio frames from NATS JetStream"],
    outputs: ["Emotional scores, stress levels, vocal patterns to Aggregator"],
    processing: "Runs wav2vec2-emotion model fine-tuned for affect detection. Outputs valence (positive/negative), arousal (calm/excited), and stress level per audio segment. Works on raw audio, not transcript — captures tone of voice, speaking rate, vocal tension.",
  },
  env: {
    title: "Environment Sound Classifier",
    explanation: "Figures out where the wearer is and what's happening around them by listening to background sounds — is this a cafe? An office? Outdoors? Is there music playing?",
    inputs: ["Raw audio frames from NATS JetStream"],
    outputs: ["Scene classification, ambient event tags, crowd density, noise floor to Aggregator"],
    processing: "Runs YAMNet model (521-class audio taxonomy). Classifies the scene (pub, office, outdoors, rural, transit, home), tags ambient events (laughter, music, traffic, birdsong, applause), estimates crowd density, and measures noise floor level.",
  },
  spk: {
    title: "Speaker Identifier",
    explanation: "Labels who is speaking — not by name, but as Speaker A, B, C. This lets Maddi track conversation dynamics without knowing anyone's identity.",
    inputs: ["Transcript + audio features from STT Engine"],
    outputs: ["Speaker labels (A, B, C...) to Aggregator"],
    processing: "Uses Resemblyzer d-vector model to create voice embeddings per audio segment, then clusters them into distinct speakers. Voiceprints are ephemeral — they exist only in container memory during processing and are never persisted (biometric data under GDPR).",
  },
  kw: {
    title: "Keyword Extractor",
    explanation: "Pulls out the important stuff from the transcript — names, places, subjects, entities. The raw building blocks that Topic Classifier organizes.",
    inputs: ["Full transcript text from STT Engine"],
    outputs: ["Extracted keywords, names, subjects to Topic Classifier", "Keywords to Aggregator"],
    processing: "Runs spaCy NER (en_core_web_trf) for named entity recognition. Extracts person names, organizations, locations, dates, and key subjects from the transcript stream.",
  },
  topic: {
    title: "Topic Classifier",
    explanation: "Takes the extracted keywords and categorizes them into meaningful topics — what is this conversation actually about?",
    inputs: ["Extracted keywords from Keyword Extractor"],
    outputs: ["Classified topics + categories to Aggregator"],
    processing: "Runs a BART-MNLI zero-shot classifier against Maddi's topic taxonomy. No training needed — it classifies keywords into topics like 'work', 'health', 'relationship', 'finances' etc. based on semantic similarity.",
  },
  agg: {
    title: "Aggregator",
    explanation: "The merging point for all real-time analysis. Collects results from all six cloud analyzers and bundles them into a single Tier 1 payload to send back to the device.",
    inputs: ["Transcripts + timestamps from STT", "Speaker labels from Speaker ID", "Keywords from Keyword Extractor", "Topics from Topic Classifier", "Emotional scores from Tonal Analyzer", "Scene/events from Environment Classifier"],
    outputs: ["Merged Tier 1 payload sent to device over existing WebSocket"],
    processing: "Subscribes to all six result streams per device via NATS subjects. Merges results on a 5-second sliding window — waits for all analyzers to report before pushing. Sends the merged payload back to the device over the same WebSocket used for audio streaming.",
  },
  hcomp: {
    title: "Hourly Compressor",
    explanation: "Every hour, takes all the raw Tier 1 signals and distills them into a compact summary — what were the main topics, how did emotions shift, what were the key moments?",
    inputs: ["Full hour of Tier 1 processed signals + consultation flags from device"],
    outputs: ["Hourly summary to Tier 2 on device"],
    processing: "Device uploads Tier 1 data via gRPC. Cloud compresses it into: dominant topics, emotional arc (start/peak/end emotional state), key moments (consultations, emotional spikes), environment profile, speaker interaction map, and motion patterns. Returns the summary; device stores it in Tier 2 and deletes the raw Tier 1 data.",
  },
  dcomp: {
    title: "Daily Compressor",
    explanation: "Once a day, takes all 24 hourly summaries and creates a day-level digest. What was the shape of the day?",
    inputs: ["Full day of Tier 2 hourly summaries from device"],
    outputs: ["Daily digest to Tier 3 on device"],
    processing: "Device uploads Tier 2 via gRPC. Cloud distills 24 hourly summaries into a daily digest: environment transitions throughout the day, emotional patterns, dominant topic themes, key interactions, and overall motion/activity profile. Device stores in Tier 3 and deletes Tier 2.",
  },
  wcomp: {
    title: "Weekly Compressor",
    explanation: "Every week, takes 7 daily digests and identifies week-level patterns — recurring themes, emotional trends, relational shifts.",
    inputs: ["Full week of Tier 3 daily digests from device"],
    outputs: ["Weekly digest to Theme Merger"],
    processing: "Device uploads Tier 3 via gRPC. Cloud distills 7 daily digests into: week-level emotional patterns, recurring topics, relational shifts (who the wearer spent time with and how dynamics changed), decision trends, and environment-mood correlations.",
  },
  merge: {
    title: "Theme Merger",
    explanation: "The most important compressor. Takes the weekly digest and merges it into the wearer's long-term theme model, applying time-decay so recent patterns matter more than old ones.",
    inputs: ["Weekly digest from Weekly Compressor", "Existing Tier 4 theme model from device"],
    outputs: ["Updated Tier 4 themes back to device", "Updated themes to Embedding Generator for vectorization"],
    processing: "Receives both the new weekly digest and the existing theme model. Merges them with time-decay weighting — recent patterns get higher weight, old patterns gradually fade unless reinforced. Updates Emotional Patterns, Relational Patterns, and Decision Patterns sub-models. Sends updated themes for re-vectorization.",
  },
  e5: {
    title: "Embedding Generator (E5-small-v2)",
    explanation: "Converts theme descriptions and queries into 384-dimensional vectors — mathematical representations that allow semantic search to find relevant themes.",
    inputs: ["Updated themes from Theme Merger (during compression)", "Transcribed query from STT (during consultation)"],
    outputs: ["Theme vectors to Tier 4d on device (during compression)", "Query vector to Semantic Search (during consultation)"],
    processing: "Runs E5-small-v2 model (ONNX) to create 384-dimensional embeddings. These vectors capture meaning — similar themes produce similar vectors, enabling the system to find relevant context without exact keyword matching. Takes ~50ms per embedding.",
  },
  qstt: {
    title: "Query STT",
    explanation: "When you press the button and speak, this is the first step — your spoken question gets converted to text. Same Deepgram engine as the passive pipeline, but dedicated to your query.",
    inputs: ["Spoken query audio from device via WebSocket"],
    outputs: ["Transcribed query text to Embedding Generator", "Transcribed query text to Context Assembler"],
    processing: "Uses Deepgram cloud STT. Transcribes the spoken query with ~800ms latency. The text goes two places: to the Embedding Generator (for semantic search) and directly to the Context Assembler (so the LLM sees the exact question).",
  },
  qemb: {
    title: "Query Embedder",
    explanation: "Takes your transcribed question and converts it into the same kind of vector as the stored themes — so the system can find which of your long-term patterns are relevant to your question.",
    inputs: ["Transcribed query text from Query STT"],
    outputs: ["Query vector to Qdrant Semantic Search"],
    processing: "Same E5-small-v2 model as the compression pipeline. Converts the query into a 384-dim vector in ~50ms. This vector is then compared against all stored theme vectors to find the most relevant context.",
  },
  qdrant: {
    title: "Qdrant Semantic Search",
    explanation: "The retrieval engine. Takes your query vector and finds which of your stored theme patterns are most relevant — not by keyword matching, but by meaning similarity.",
    inputs: ["Query vector from Embedding Generator", "Stored theme vectors from Tier 4d on device"],
    outputs: ["Relevant theme subset to Context Assembler"],
    processing: "Uses HNSW (Hierarchical Navigable Small World) algorithm for fast approximate nearest-neighbor search. Per-device collection is small (hundreds of vectors), loaded into memory on demand. Returns the top relevant themes in ~20ms. These are the memories the LLM will use to understand your question.",
  },
  asm: {
    title: "Context Assembler",
    explanation: "Gathers everything the LLM needs to give good advice: your question, relevant long-term themes, what's happening right now (Tier 1), today's summary (Tier 2), and this week's patterns (Tier 3).",
    inputs: ["Relevant themes from Semantic Search", "Current hour's signals from Tier 1", "Today's hourly summaries from Tier 2", "This week's daily digests from Tier 3", "Transcribed query text from STT"],
    outputs: ["Full assembled context package to the LLM"],
    processing: "Template-based concatenation — combines all context sources into a structured prompt. No ML involved, just careful ordering: query first, then current context (Tier 1), then broader context (Tier 2/3), then relevant long-term themes. Takes ~10ms.",
  },
  haiku: {
    title: "Deep Reasoner (LLM)",
    explanation: "The reasoning engine of the consultation pipeline. Takes the full assembled context — the user's question, current signals, daily and weekly summaries, and relevant long-term themes — and produces comprehensive internal reasoning. This output is rich, detailed, and never shown to the user. It exists solely as input for the Glyph Picker, which translates it into symbolic form.",
    inputs: ["Full context package from Context Assembler"],
    outputs: ["Full reasoning output to Glyph Picker"],
    processing: "Runs an LLM (OpenAI or Claude) with a system prompt instructing deep reasoning about the query in the context of the wearer's life patterns. The output is unconstrained internal reasoning (~200-500 tokens). ~1500ms inference time. On timeout (>3s), retries once with shorter context (drops Tier 3). If still fails, returns error glyph + 'busy'.",
  },
  rule: {
    title: "Rule Constraint Layer",
    explanation: "A validation gate between the Glyph Picker and the E-Ink display. Checks that the output contains exactly 3 valid glyph IDs from the current inventory, no duplicates, and a single word within length constraints. Rejects and retries up to 2 times. If validation still fails, falls back to top-3 glyphs by relevance score.",
    inputs: ["Proposed glyph selection from Glyph Picker: 3 glyph IDs + 1 word"],
    outputs: ["Validated 3 glyphs + word to E-Ink display on device", "Response-ready haptic signal"],
    processing: "Deterministic validation layer. Checks: all 3 glyph IDs exist in current inventory, no duplicate IDs, word is a single English word under 15 characters. If invalid, retries Glyph Picker up to 2 times. Final fallback: top-3 by relevance_score + most common noun from Deep Reasoner output. Takes ~5ms.",
  },
  wifiprov: {
    title: "WiFi Provisioning",
    explanation: "How the wearer sets up WiFi on their Maddi for the first time. The companion app scans for networks, the wearer picks one and enters the password, and it's sent securely over Bluetooth.",
    inputs: ["WiFi SSID + password from Companion App via BLE"],
    outputs: ["Encrypted credentials stored in NVS flash"],
    processing: "Uses SRP6a/X25519 key agreement over BLE for a secure channel — even if someone intercepts the Bluetooth signal, they can't read the credentials. Credentials are stored in ESP32's encrypted NVS partition (AES-XTS with eFuse-bound key).",
  },
  socialmgr: {
    title: "Social Manager",
    explanation: "The companion app screen where you manage connections with other Maddi wearers — who you trust, what you share, and who you've blocked.",
    inputs: ["User preferences for sharing levels and trusted devices"],
    outputs: ["Trust configuration sent to device BLE handler"],
    processing: "Manages a trusted device list with per-device sharing levels: Level 0 (presence only), Level 1 (+ environment), Level 2 (+ topic overlap + emotional valence). Both devices must consent — data flows at the minimum level agreed by both.",
  },
  crypto: {
    title: "Crypto-Shredding",
    explanation: "The nuclear option for privacy. Each tier's data is encrypted with its own key stored in the ESP32's eFuse-protected block. Deleting the key makes all that tier's data permanently unrecoverable — without touching the flash.",
    inputs: ["Deletion command from Companion App via cloud"],
    outputs: ["Tier data rendered cryptographically unrecoverable"],
    processing: "Each tier is encrypted with a per-tier AES-256-GCM key. On deletion request: cloud deletes backups and its key envelope, then sends wipe command to device. Device deletes the tier's encryption key from eFuse-protected storage. Signs a DeletionAttestation that the app can verify.",
  },
  pot: {
    title: "Potentiometer",
    explanation: "A physical dial on the device that lets the wearer adjust E-Ink display contrast without opening the companion app.",
    inputs: ["Analog voltage from wearer turning the dial"],
    outputs: ["Contrast level to E-Ink display controller"],
    processing: "Connected to GPIO 8 (ADC). The ESP32 reads the analog value, maps it to a contrast range, and updates the E-Ink display's LUT (look-up table) accordingly. No cloud involvement — purely local hardware control.",
  },
  haptic: {
    title: "Haptic Motor (DRV2605L)",
    explanation: "A small vibration motor that provides tactile feedback — a short buzz when the button is pressed and a distinct pattern when a consultation response arrives on the E-Ink display.",
    inputs: ["Button press event from GPIO ISR", "Response-ready signal from Rule Constraint Layer"],
    outputs: ["Vibration pattern felt by the wearer"],
    processing: "Driven by a DRV2605L haptic driver over I2C. Two patterns: a quick 50ms tap on button press (confirmation), and a double-pulse pattern when a consultation response is rendered on E-Ink. Draws up to 80mA peak during vibration.",
  },
  wifi: {
    title: "WiFi Credentials",
    explanation: "The stored WiFi credentials that allow the device to connect to the internet for cloud communication. Written once during provisioning and encrypted at rest.",
    inputs: ["Encrypted credentials from BLE provisioning flow"],
    outputs: ["WiFi connection parameters to the ESP32 WiFi stack"],
    processing: "Stored in the ESP32's encrypted NVS partition (AES-XTS with eFuse-bound key). On boot, the WiFi stack reads credentials from NVS to establish the mTLS tunnel to the API Gateway.",
  },
  gw: {
    title: "API Gateway (Kong)",
    explanation: "The single entry point for all device-to-cloud traffic. Every WebSocket, gRPC, and REST call from the device passes through Kong, which handles mutual TLS authentication, rate limiting, and routing.",
    inputs: ["All device traffic: audio streams, tier uploads, consultation queries"],
    outputs: ["Routed traffic to internal cloud services (NATS, STT, compressors)"],
    processing: "Runs Kong API Gateway with mTLS (device presents a client certificate signed by the Maddi CA). Enforces TLS 1.3, per-device rate limiting, and routes requests to the correct internal service. All cloud services are behind Kong — no direct device-to-service connections.",
  },
  devstatus: {
    title: "Device Status",
    explanation: "A companion app screen showing the device's current state — battery level, connectivity, active pipeline status, and storage usage across tiers.",
    inputs: ["Status telemetry from device via BLE"],
    outputs: ["Visual status dashboard in the companion app"],
    processing: "The device periodically advertises status over BLE: battery percentage, WiFi signal strength, current pipeline state (idle/listening/consulting), and per-tier storage usage. The companion app renders this as a live dashboard.",
  },
  tierview: {
    title: "Tier Viewer",
    explanation: "A companion app screen that lets the wearer browse their tier data — what topics were captured, emotional patterns, and long-term themes. Read-only access to the wearer's own memory.",
    inputs: ["Tier summaries from device via BLE"],
    outputs: ["Browsable tier data in the companion app"],
    processing: "On request, the device transmits tier summaries over BLE (not raw data — only the compressed summaries). The companion app renders them in a timeline view with topic, emotion, and environment breakdowns.",
  },
  privctrl: {
    title: "Privacy Controls",
    explanation: "The companion app screen where the wearer manages all privacy settings — data retention periods, tier deletion, export requests, and recording preferences.",
    inputs: ["User privacy preferences from the companion app UI"],
    outputs: ["Privacy configuration to device via BLE", "Deletion/export commands to Privacy & Compliance zone"],
    processing: "Provides controls for: per-tier retention periods, immediate tier deletion (triggers crypto-shredding), data export (GDPR Art. 20), right to erasure (GDPR Art. 17), and recording indicator preferences. All changes are signed and sent to the device over BLE.",
  },
  ota: {
    title: "OTA Firmware Update",
    explanation: "Secure over-the-air firmware updates delivered from the cloud. The device pulls new firmware through the API Gateway and verifies it with Ed25519 signatures before flashing.",
    inputs: ["Signed firmware image from cloud via API Gateway"],
    outputs: ["Updated firmware flashed to ESP32"],
    processing: "The companion app notifies the wearer of available updates. On approval, the device downloads the firmware image over WiFi through Kong. The image is Ed25519-signed — the device verifies the signature against a pinned public key before flashing. Supports rollback to the previous version if boot fails.",
  },
  consent: {
    title: "Consent Settings",
    explanation: "Granular consent management in the companion app — the wearer explicitly opts in or out of specific data processing types, including biometric (voiceprint) processing.",
    inputs: ["User consent choices from the companion app UI"],
    outputs: ["Consent flags to device and cloud pipelines", "Biometric consent state to Biometric Consent gate"],
    processing: "Manages per-category consent: audio capture, environmental analysis, emotional analysis, speaker identification (biometric), social sharing. Consent state is cryptographically signed and stored both on-device and in the cloud. Changes take effect immediately — revoking biometric consent disables the Speaker Identifier pipeline.",
  },
  othermaddi: {
    title: "Other Maddi Device",
    explanation: "Another Maddi device worn by someone nearby. When two Maddi wearers are in proximity, their devices can exchange limited social context over BLE — presence, shared environment, and (if both consent) topic overlap.",
    inputs: ["BLE advertising packets from a nearby Maddi device"],
    outputs: ["Encrypted social context packets to BLE Radio"],
    processing: "Discovered via BLE advertising with the Maddi UUID. Both devices must have each other in their trusted device list. Data exchange uses Ed25519-signed packets at the minimum sharing level agreed by both: Level 0 (presence only), Level 1 (+ environment), Level 2 (+ topic overlap + emotional valence).",
  },
  nvs: {
    title: "NVS Encrypted Storage",
    explanation: "The ESP32's encrypted Non-Volatile Storage partition that holds WiFi credentials and per-tier encryption keys. Protected by an eFuse-bound AES-XTS key that cannot be read by software.",
    inputs: ["WiFi credentials from provisioning flow", "Per-tier encryption keys generated at setup"],
    outputs: ["Credentials to WiFi stack on boot", "Tier keys to crypto-shredding module on deletion"],
    processing: "Uses the ESP32's hardware-encrypted NVS partition. The AES-XTS encryption key is stored in eFuse block 1 and is only accessible by the flash encryption hardware — not readable by any software, including firmware. This is the root of trust for all on-device encryption.",
  },
  erasure: {
    title: "Right to Erasure (GDPR Art. 17)",
    explanation: "Implements the GDPR right to erasure — the wearer can request complete deletion of all their data. This triggers crypto-shredding of all tier keys, making all stored data permanently unrecoverable.",
    inputs: ["Erasure request from Privacy Controls in companion app"],
    outputs: ["Crypto-shredding command to destroy all tier encryption keys"],
    processing: "On erasure request: (1) cloud deletes all server-side data and key envelopes, (2) device triggers crypto-shredding for all tiers, (3) device signs a DeletionAttestation proving the data was destroyed, (4) companion app receives and displays the attestation. Irreversible.",
  },
  dataexp: {
    title: "Data Export (GDPR Art. 20)",
    explanation: "Implements GDPR data portability — the wearer can export all their data in a machine-readable format. Exports long-term themes and tier summaries as JSON + a human-readable PDF.",
    inputs: ["Export request from Privacy Controls", "Theme data from Tier 4"],
    outputs: ["JSON + PDF export package to companion app"],
    processing: "On export request: reads all tier summaries and Tier 4 themes from the device, packages them as structured JSON (machine-readable) and a formatted PDF (human-readable). The export includes: all theme patterns, emotional history, topic history, and consultation history. Delivered to the companion app for download.",
  },
  recindicator: {
    title: "Recording Indicator",
    explanation: "A hardwired LED that is physically connected to the microphone power line — it is impossible to record audio without the LED being lit. This is a privacy-critical hardware guarantee, not a software feature.",
    inputs: ["Microphone power state (hardwired electrical connection)"],
    outputs: ["Visible LED indicator to people around the wearer"],
    processing: "The LED is wired in series with the INMP441 microphone's power supply. When the mic draws current, the LED lights up. There is no software control — this is a hardware guarantee that recording cannot happen invisibly. Complies with two-party consent recording laws.",
  },
  biometric: {
    title: "Biometric Consent Gate",
    explanation: "A privacy gate that controls whether voiceprint processing (Speaker Identifier) is allowed. Under GDPR, biometric data requires explicit opt-in consent. Without it, the Speaker Identifier pipeline is disabled.",
    inputs: ["Consent state from Consent Settings in companion app"],
    outputs: ["Enable/disable signal to Speaker Identifier pipeline"],
    processing: "Reads the biometric consent flag from the device's consent store. If consent is granted, the Speaker Identifier runs normally. If revoked or never granted, the Speaker Identifier is disabled and all audio segments are labeled 'unknown speaker'. Voiceprint consent is separate from general audio consent.",
  },
  glyphstore: {
    title: "Glyph Inventory",
    explanation: "The on-device store of 22 glyphs — Maddi's symbolic vocabulary. Each glyph is a 200×200 1-bit bitmap in 8-bit/16-bit artistic style, stored with rich metadata: labels, tags, interpretations, stories, and a 384-dim embedding vector. The default 22 are hand-crafted by the Maddi team and ship with every device. Over time, the cloud-side Glyph Engine replaces 2–3 per week with generated glyphs personalized to the wearer's evolving themes.",
    inputs: ["New glyphs + metadata from Glyph Embedder (weekly)", "Glyph metadata requests from Glyph Picker (consultation)"],
    outputs: ["Full 22-glyph inventory with metadata to Glyph Picker", "Current inventory to Glyph Engine (for diversity checks)", "Encryption keys to Crypto-Shredding on deletion"],
    processing: "Stored in a dedicated 256KB flash partition (glyph_store), separate from tier data. Each glyph is ~5KB (1-bit PBM) plus ~5-10KB protobuf metadata. Encrypted with its own AES-256-GCM key (eFuse-protected), enabling independent crypto-shredding. Writes go through StorageManager like all flash operations. Relevance scores are recomputed after each weekly Theme Merger.",
  },
  glyphpicker: {
    title: "Glyph Picker",
    explanation: "The narrative composer. A fast Haiku-class LLM that translates the Deep Reasoner's internal analysis into Maddi's symbolic output: 3 glyphs ordered as a story arc (setup → tension → resolution) plus 1 closing word. This is where Maddi's philosophy is enacted — nudge, don't prescribe. The Glyph Picker sees the full reasoning, the multi-tier context, and all 22 glyphs with their metadata, then composes a symbolic response the user interprets for themselves.",
    inputs: ["Deep Reasoner's full reasoning output", "Multi-tier context from Context Assembler", "Full 22-glyph inventory with labels, tags, interpretations, and stories from Glyph Store"],
    outputs: ["Ordered glyph sequence [id, id, id] + one word to Rule Constraint Layer"],
    processing: "A single Haiku-class LLM call (~300-500ms). The model receives the Deep Reasoner's output, compressed multi-tier context, and all 22 glyph metadata records. It selects 3 glyphs for narrative arc and one English word as closing punctuation. Output schema: {glyph_sequence: [3 ids], word: string, narrative_thread: string (internal)}. On timeout (>1s), falls back to top-3 by relevance_score + most common noun from reasoning.",
  },
  glyphengine: {
    title: "Glyph Engine",
    explanation: "The weekly glyph generator. Runs after the Theme Merger completes as the final step of the compression cascade. Takes the wearer's updated Tier 4 themes and the current 22-glyph inventory, then generates 2–3 new glyphs with full metadata to replace the least relevant ones. This keeps the symbolic vocabulary evolving with the wearer's life.",
    inputs: ["Updated Tier 4 themes from Theme Merger", "Current 22-glyph inventory from Glyph Store (for diversity)"],
    outputs: ["New glyph images + metadata to Glyph Embedder for vectorization"],
    processing: "Custom image generation model produces 200×200 1-bit glyph art conditioned on Tier 4 themes. Generates labels, tags, 5-10 interpretations, and 2-3 stories per glyph. Checks pairwise cosine similarity against surviving glyphs to ensure diversity. Replaces glyphs with highest semantic distance from current themes and lowest selection count. Minimum glyph lifespan: 1 week. Turnover: 2-3 per week (~10-14%).",
  },
  glyphembed: {
    title: "Glyph Embedder",
    explanation: "Converts new glyph metadata into 384-dimensional vectors using the same E5-small-v2 model as the theme and query embedders. These vectors enable the relevance scoring system that determines which glyphs get replaced.",
    inputs: ["New glyph metadata (labels, tags, interpretations, stories) from Glyph Engine"],
    outputs: ["Glyph metadata + 384-dim embedding vectors to Glyph Store on device"],
    processing: "Runs E5-small-v2 (ONNX) to embed the concatenated text of each glyph's labels, tags, and interpretations into a 384-dim vector. These vectors are compared against Tier 4 theme embeddings to compute relevance scores. Takes ~50ms per glyph. New glyphs are packaged with their vectors and delivered to the device via the weekly compression gRPC response.",
  },
};
