/* Node info data — explanations, inputs, outputs, processing for each pipeline node (v5 architecture) */

export interface NodeInfo {
  title: string;
  explanation: string;
  inputs: string[];
  outputs: string[];
  processing: string;
}

export const NODE_INFO: Record<string, NodeInfo> = {
  mic: {
    title: "INMP441 Microphone",
    explanation: "An always-on MEMS microphone that captures full environment audio. It listens to everything around the wearer — conversations, ambient sounds, background noise.",
    inputs: ["Raw sound waves from the environment"],
    outputs: ["16-bit PCM audio stream via I2S bus to ESP32"],
    processing: "Converts acoustic pressure waves into a digital audio signal at 16kHz sample rate. Consumes only 1.4mW. Runs continuously — there is no off switch (a hardwired LED indicates when it's active).",
  },
  vad: {
    title: "ESP-SR Voice Activity Detection",
    explanation: "A local neural network on Core 0 of the ESP32 that listens to the audio and decides: is someone speaking right now? This is the power gatekeeper — WiFi only turns on when speech is detected.",
    inputs: ["Raw PCM audio from PSRAM ring buffer"],
    outputs: ["Speech/silence decision", "WiFi power-on trigger when speech starts"],
    processing: "Runs an energy-based pre-filter (<0.5ms) to reject obvious silence, then ESP-SR WakeNet neural model for accurate speech detection. When speech starts, signals the WiFi radio to power on. Keeps WiFi alive for 2s after speech ends to catch pauses.",
  },
  opus: {
    title: "Opus Encoder",
    explanation: "Compresses the raw audio into a much smaller stream before sending it to the cloud. Without this, streaming would use 15x more bandwidth.",
    inputs: ["Raw PCM audio from the ring buffer (only when VAD says speech is active)"],
    outputs: ["Opus-compressed audio frames at 16kbps to WiFi streamer"],
    processing: "Encodes 20ms audio frames using the Opus codec on Core 1. Reduces 256kbps raw audio down to ~16kbps — a 16x compression. Runs in real-time with no perceptible delay.",
  },
  imu: {
    title: "6DoF IMU (GY-521 MPU-6050)",
    explanation: "A motion sensor with accelerometer + gyroscope that tracks the wearer's physical state — walking, sitting, fidgeting, lying down.",
    inputs: ["Physical acceleration and rotation from the wearer's body"],
    outputs: ["Processed motion state classification to Tier 1"],
    processing: "The ESP32 communicates with the MPU-6050 over I2C (SCL: 39, SDA: 38) at 25Hz and classifies the raw accelerometer/gyroscope vectors into motion states: walking, sitting, fidgeting, lying down, and transitions between them. Draws ~3.5mA.",
  },
  btn: {
    title: "Physical Button",
    explanation: "The only way the wearer actively interacts with Maddi. One press means: 'I have a question — listen to what I say next and give me advice.'",
    inputs: ["Physical button press from the wearer"],
    outputs: ["Activates microphone for query capture", "Triggers consultation flow via Edge Function", "Writes consultation flag to Tier 1"],
    processing: "A hardware interrupt fires on press. This does three things: (1) signals the mic to start capturing the spoken query, (2) kicks off the consultation pipeline via the /consult Edge Function, and (3) marks this moment in Tier 1 with an elevated weight so compressors know this was an important moment.",
  },
  t1: {
    title: "Tier 1: Processed Signals",
    explanation: "The first layer of Maddi's memory. Stores the last hour of everything that's been understood from the audio — what was said, how people felt, where the wearer was.",
    inputs: ["Transcripts and analysis from Supabase /ingest-audio Edge Function", "Motion state from IMU", "Consultation flags from Button"],
    outputs: ["Sent to Hourly Compressor Edge Function every hour", "Sent to /consult Edge Function during consultation"],
    processing: "Stored as rows in Supabase Postgres (tier_1 table). Each signal type has a timestamp. After hourly compression, the raw signals are deleted to save space. During consultation, current signals are fetched by the /consult Edge Function so the LLM has real-time context.",
  },
  t2: {
    title: "Tier 2: Daily Digest",
    explanation: "A summary of the day so far, built from hourly summaries. Captures the arc of the day — what topics dominated, how emotions shifted, key moments.",
    inputs: ["Hourly summaries from the Hourly Compressor Edge Function"],
    outputs: ["Sent to Daily Compressor Edge Function every 24 hours", "Fetched by /consult Edge Function during consultation"],
    processing: "Stored in Supabase Postgres (tier_2 table). Accumulates up to 24 hourly summaries. Each summary contains dominant topics, emotional arc, key moments, environment profile, and motion patterns. After daily compression, the hourly summaries are deleted.",
  },
  t3: {
    title: "Tier 3: Weekly Digest",
    explanation: "A week-level view that reveals patterns you can't see in a single day — recurring topics, emotional trends, shifting relationships, decision habits.",
    inputs: ["Daily digests from the Daily Compressor Edge Function"],
    outputs: ["Sent to Weekly Compressor Edge Function every 7 days", "Fetched by /consult Edge Function during consultation"],
    processing: "Stored in Supabase Postgres (tier_3 table). Accumulates 7 daily digests. Captures week-level emotional patterns, recurring topics, relational shifts, decision trends, and environment-mood correlations. After weekly compression, the daily digests are deleted.",
  },
  t4: {
    title: "Tier 4: Long-Term Themes",
    explanation: "Maddi's deep memory — the patterns of who you are over months and years. Stress triggers, key relationships, decision habits, places that affect your mood. This is what makes Maddi's advice personal.",
    inputs: ["Updated themes from Theme Merger Edge Function (weekly)"],
    outputs: ["Existing themes sent to Theme Merger for updates", "Themes fetched by /consult Edge Function during consultation", "Encrypted storage keys linked to Crypto-Shredding"],
    processing: "Stored in Supabase Postgres (tier_4 table) with row-level security. Contains four sub-models: Emotional Patterns (stress triggers, mood cycles), Relational Patterns (key people, social dynamics), Decision Patterns (uncertainty types, reasoning habits). Uses a 2-year rolling window with time-decay — old patterns gradually fade unless reinforced. Encrypted at rest via Supabase's disk encryption.",
  },
  eink: {
    title: "E-Ink Display (296x128)",
    explanation: "Maddi's output surface. A 200x200 binary E-Ink display that shows consultation responses as a scrollable sequence: 3 glyphs (one at a time, full-screen) followed by a single word, navigated by the potentiometer. Each glyph fills the entire screen — the wearer turns the dial to advance through the narrative arc. The display holds the last consultation between queries at zero power cost.",
    inputs: ["Validated 3 glyphs + word from Rule Constraint Layer", "Scroll position from potentiometer (5 zones)"],
    outputs: ["Visual display of glyphs and word to the wearer"],
    processing: "Connected via SPI (CS:10, DIN:11, CLK:12, DC:13, RST:14, BUSY:9). Potentiometer ADC (GPIO 8) is software-thresholded into 5 zones with +/-50 hysteresis: zones 0-2 show glyphs 1-3 (full screen 200x200 bitmaps), zone 3 shows the word (centered, large type), zone 4 shows last query text. E-Ink refreshes only on zone change — 8mA per refresh, zero power to hold. Idle state: scrollable view of last consultation.",
  },
  ble: {
    title: "BLE Radio",
    explanation: "The Bluetooth radio handles WiFi provisioning from the companion app.",
    inputs: ["Encrypted WiFi credentials from Companion App"],
    outputs: ["WiFi credentials to credential store"],
    processing: "Uses the ESP32's shared 2.4GHz radio (time-sliced with WiFi). For provisioning: SRP6a/X25519 key agreement.",
  },
  /* ── Supabase Cloud nodes ── */
  "supabase-auth": {
    title: "Supabase Auth",
    explanation: "Handles device and user authentication. Each device registers with a JWT and all Edge Function calls are authenticated via Supabase Auth tokens. Replaces the old Kong mTLS gateway.",
    inputs: ["Device registration from companion app", "Auth tokens from device WiFi stack"],
    outputs: ["Authenticated session to Edge Functions", "Row-level security policies for Postgres"],
    processing: "Supabase Auth issues JWTs per device. The device includes its JWT in every request. Edge Functions validate the token before processing. Row-level security (RLS) policies on all tier tables ensure a device can only access its own data.",
  },
  "supabase-realtime": {
    title: "Supabase Realtime",
    explanation: "Provides real-time WebSocket channels for streaming audio from the device to the /ingest-audio Edge Function and pushing consultation responses back to the device.",
    inputs: ["Opus audio stream from device", "Consultation responses from /consult Edge Function"],
    outputs: ["Audio frames to /ingest-audio Edge Function", "Consultation results pushed to device"],
    processing: "Uses Supabase Realtime channels over WebSocket. The device opens a channel on speech detection and streams Opus frames. Responses from the /consult Edge Function are pushed back on the same channel. Replaces the old NATS JetStream fan-out.",
  },
  "edge-ingest": {
    title: "Edge Fn: /ingest-audio",
    explanation: "A Supabase Edge Function that receives the audio stream, sends it to Deepgram STT, and writes the resulting transcripts and analysis directly into Tier 1 in Postgres. Replaces the entire real-time analysis pipeline (NATS, STT, Tonal, Environment, Speaker ID, Keywords, Topics, Aggregator).",
    inputs: ["Opus audio frames via Supabase Realtime channel"],
    outputs: ["Transcripts and processed signals written to Tier 1 (Postgres)"],
    processing: "Receives Opus audio frames, forwards them to Deepgram's cloud STT API for real-time transcription with ~800ms latency. Writes timestamped transcript segments, detected topics, and emotional indicators directly to the tier_1 table in Postgres. No separate fan-out to multiple analyzers — the LLM handles deeper analysis during consultation.",
  },
  "edge-consult": {
    title: "Edge Fn: /consult",
    explanation: "The consultation Edge Function. When the wearer presses the button, this function transcribes the query via Deepgram, fetches context from all four tiers in Postgres, calls the LLM to generate 3 glyphs + 1 word, validates the output, and returns it to the device.",
    inputs: ["Spoken query audio from device via Supabase Realtime", "Tier 1-4 context from Postgres"],
    outputs: ["Validated 3 glyphs + 1 word to Rule Constraint, then to device"],
    processing: "Pipeline: (1) Deepgram STT transcribes query (~800ms), (2) Fetch current Tier 1-4 context from Postgres, (3) LLM call (OpenAI or Claude) with system prompt, all context, query text, and the 22 glyph metadata — selects 3 glyphs as narrative arc + 1 word (~1500ms), (4) Rule Constraint validation (3 valid glyph IDs, no duplicates, single word <15 chars), (5) Return to device. Total ~2.5s.",
  },
  pgcron: {
    title: "pg_cron Scheduler",
    explanation: "Supabase's built-in cron scheduler that triggers the compression Edge Functions on schedule. Replaces the old K8s CronJobs.",
    inputs: ["Cron schedule configuration"],
    outputs: ["Triggers to compression Edge Functions (hourly, daily, weekly)"],
    processing: "Runs inside Postgres via the pg_cron extension. Schedules: hourly compression every hour, daily compression every 24h, weekly compression + theme merge every 7 days. Each trigger invokes the corresponding Supabase Edge Function via pg_net HTTP calls.",
  },
  postgres: {
    title: "Postgres (Tier Tables)",
    explanation: "The Supabase-managed Postgres database that stores all tier data, glyph metadata, and device configuration. Replaces on-device flash storage for cloud-side data and the separate Qdrant vector DB.",
    inputs: ["Tier data from Edge Functions", "Glyph metadata", "Device configuration"],
    outputs: ["Tier data to Edge Functions on query", "Context data to /consult Edge Function"],
    processing: "Tables: tier_1 (signals), tier_2 (daily), tier_3 (weekly), tier_4 (themes), glyphs (22 glyph metadata), devices (config). All tables have RLS policies scoped to device_id. No vector search — the LLM reads tier data directly. Supabase handles backups, encryption at rest, and connection pooling.",
  },
  "supabase-storage": {
    title: "Supabase Storage",
    explanation: "Object storage for glyph bitmap images. The 22 glyph PBM files are stored here and served to the device when needed.",
    inputs: ["Glyph bitmap files (200x200 1-bit PBM)"],
    outputs: ["Glyph images to device on request"],
    processing: "Stores the 22 glyph bitmaps (~5KB each) in a per-device bucket. RLS policies restrict access to the owning device. Images are cached on the device after first download. Total storage per device: ~110KB.",
  },
  /* ── Consultation pipeline nodes (simplified) ── */
  qstt: {
    title: "Query STT",
    explanation: "When you press the button and speak, this is the first step — your spoken question gets converted to text. Deepgram STT running inside the /consult Edge Function.",
    inputs: ["Spoken query audio from device via Supabase Realtime"],
    outputs: ["Transcribed query text to context fetch step"],
    processing: "Uses Deepgram cloud STT within the /consult Edge Function. Transcribes the spoken query with ~800ms latency. The text is passed to the next step where context is fetched from Postgres.",
  },
  fetchctx: {
    title: "Fetch Context",
    explanation: "Reads the wearer's current context from all four tiers in Postgres. No vector search or embeddings — just direct SQL queries scoped to the device.",
    inputs: ["Transcribed query text from Query STT", "Device ID from auth token"],
    outputs: ["Assembled context package (Tier 1-4 data + query) to LLM"],
    processing: "Runs inside the /consult Edge Function. Queries: current hour from tier_1, today's summary from tier_2, this week's digest from tier_3, long-term themes from tier_4, and the 22 glyph metadata from the glyphs table. Assembles everything into a structured prompt. Takes ~50ms (all data in same Postgres instance).",
  },
  deepreasoner: {
    title: "Deep Reasoner",
    explanation: "The first stage of a two-stage LLM architecture. A full-size model (OpenAI / Claude) receives the assembled context and the user's query. It produces comprehensive internal reasoning — what the user is really asking, relevant patterns from their history, emotional context, and multiple perspectives. This output is never shown to the user; it exists solely as input for the Glyph Picker.",
    inputs: ["Full context package from Fetch Context (query + Tier 1-4 data)"],
    outputs: ["Internal reasoning text (~200-500 tokens) to Glyph Picker"],
    processing: "Runs OpenAI or Claude with a system prompt: reason about the user's situation, emotional undercurrents, and what they're really asking beneath the surface question. No format constraints — free-form analysis. ~1500ms inference. Does NOT see the glyph inventory, does NOT select glyphs.",
  },
  glyphpicker: {
    title: "Glyph Picker",
    explanation: "The second stage receives the Deep Reasoner's full analysis, the same multi-tier context, and the complete 22-glyph inventory with all metadata (labels, tags, interpretations, stories). In a single Haiku-class LLM call, it selects 3 glyphs ordered as a narrative arc (setup, tension, resolution) and 1 companion word (max 15 chars).",
    inputs: ["Deep Reasoner's internal reasoning", "Multi-tier context package", "22-glyph inventory with full metadata"],
    outputs: ["3 glyph IDs + 1 word to Rule Constraint"],
    processing: "Runs a Haiku-class LLM. The prompt includes the Deep Reasoner's analysis, the context package, and all 22 glyph metadata entries (~1200 tokens of glyph data). Output schema: {glyph_sequence: [3 ids], word: string, narrative_thread: string}. ~400ms inference.",
  },
  rule: {
    title: "Rule Constraint Layer",
    explanation: "A validation gate between the LLM and the E-Ink display. Checks that the output contains exactly 3 valid glyph IDs from the inventory, no duplicates, and a single word within length constraints. Rejects and retries up to 2 times.",
    inputs: ["Proposed glyph selection from Glyph Picker: 3 glyph IDs + 1 word"],
    outputs: ["Validated 3 glyphs + word to E-Ink display on device", "Response-ready haptic signal"],
    processing: "Deterministic validation layer inside the /consult Edge Function. Checks: all 3 glyph IDs exist in the glyphs table, no duplicate IDs, word is a single English word under 15 characters. If invalid, retries Glyph Picker up to 2 times. Final fallback: top-3 by relevance + most common noun from Deep Reasoner output. Takes ~5ms.",
  },
  /* ── Compression (Edge Functions triggered by pg_cron) ── */
  hcomp: {
    title: "Hourly Compressor",
    explanation: "Every hour, a Supabase Edge Function takes all the raw Tier 1 signals and distills them into a compact summary — what were the main topics, how did emotions shift, what were the key moments?",
    inputs: ["Full hour of Tier 1 rows from Postgres"],
    outputs: ["Hourly summary written to Tier 2 in Postgres"],
    processing: "Triggered by pg_cron every hour. Reads tier_1 rows for the past hour, compresses into: dominant topics, emotional arc, key moments (consultations, emotional spikes), environment profile, and motion patterns. Writes the summary to tier_2 and deletes the processed tier_1 rows.",
  },
  dcomp: {
    title: "Daily Compressor",
    explanation: "Once a day, takes all 24 hourly summaries and creates a day-level digest. What was the shape of the day?",
    inputs: ["Full day of Tier 2 hourly summaries from Postgres"],
    outputs: ["Daily digest written to Tier 3 in Postgres"],
    processing: "Triggered by pg_cron every 24 hours. Reads tier_2 rows for the past day, distills into a daily digest: environment transitions, emotional patterns, dominant topics, key interactions, and activity profile. Writes to tier_3 and deletes processed tier_2 rows.",
  },
  wcomp: {
    title: "Weekly Compressor",
    explanation: "Every week, takes 7 daily digests and identifies week-level patterns — recurring themes, emotional trends, relational shifts.",
    inputs: ["Full week of Tier 3 daily digests from Postgres"],
    outputs: ["Weekly digest to Theme Merger"],
    processing: "Triggered by pg_cron every 7 days. Reads tier_3 rows for the past week, distills into: week-level emotional patterns, recurring topics, relational shifts, decision trends, and environment-mood correlations.",
  },
  merge: {
    title: "Theme Merger",
    explanation: "The most important compressor. Takes the weekly digest and merges it into the wearer's long-term theme model, applying time-decay so recent patterns matter more than old ones.",
    inputs: ["Weekly digest from Weekly Compressor", "Existing Tier 4 theme model from Postgres"],
    outputs: ["Updated Tier 4 themes written to Postgres"],
    processing: "Runs as a Supabase Edge Function triggered after weekly compression. Reads the new weekly digest and existing tier_4 themes. Merges with time-decay weighting — recent patterns get higher weight, old patterns gradually fade unless reinforced. Updates Emotional, Relational, and Decision pattern sub-models. Writes back to tier_4.",
  },
  /* ── On-device glyph store ── */
  glyphstore: {
    title: "Glyph Inventory",
    explanation: "The on-device store of 22 static glyphs — Maddi's symbolic vocabulary. Each glyph is a 200x200 1-bit bitmap with rich metadata: labels, tags, interpretations, and stories. The 22 glyphs are hand-crafted by the Maddi team and ship with every device. They do not change over time (no generation engine).",
    inputs: ["Glyph metadata from Postgres glyphs table", "Glyph bitmaps from Supabase Storage"],
    outputs: ["Full 22-glyph inventory with metadata to /consult Edge Function"],
    processing: "Stored in a dedicated 256KB flash partition (glyph_store), separate from tier data. Each glyph is ~5KB (1-bit PBM) plus ~5-10KB protobuf metadata. The LLM receives all 22 glyph metadata records during consultation and picks 3. No embeddings, no vector search, no weekly generation.",
  },
  /* ── Companion App nodes ── */
  wifiprov: {
    title: "WiFi Provisioning",
    explanation: "How the wearer sets up WiFi on their Maddi for the first time. The companion app scans for networks, the wearer picks one and enters the password, and it's sent securely over Bluetooth.",
    inputs: ["WiFi SSID + password from Companion App via BLE"],
    outputs: ["Encrypted credentials stored in NVS flash"],
    processing: "Uses SRP6a/X25519 key agreement over BLE for a secure channel — even if someone intercepts the Bluetooth signal, they can't read the credentials. Credentials are stored in ESP32's encrypted NVS partition (AES-XTS with eFuse-bound key).",
  },
  devstatus: {
    title: "Device Status",
    explanation: "A companion app screen showing the device's current state — battery level, connectivity, active pipeline status, and storage usage across tiers.",
    inputs: ["Status telemetry from device via BLE"],
    outputs: ["Visual status dashboard in the companion app"],
    processing: "The device periodically advertises status over BLE: battery percentage, WiFi signal strength, current pipeline state (idle/listening/consulting), and per-tier storage usage. The companion app renders this as a live dashboard.",
  },
  tierview: {
    title: "Tier Viewer",
    explanation: "A companion app screen that lets the wearer browse their tier data — what topics were captured, emotional patterns, and long-term themes. Read-only access to the wearer's own memory.",
    inputs: ["Tier summaries from Supabase Postgres via companion app API"],
    outputs: ["Browsable tier data in the companion app"],
    processing: "The companion app authenticates via Supabase Auth and queries tier summaries directly from Postgres (RLS-scoped). Renders them in a timeline view with topic, emotion, and environment breakdowns.",
  },
  privctrl: {
    title: "Privacy Controls",
    explanation: "The companion app screen where the wearer manages all privacy settings — data retention periods, tier deletion, export requests, and recording preferences.",
    inputs: ["User privacy preferences from the companion app UI"],
    outputs: ["Privacy configuration to device via BLE", "Deletion/export commands to Privacy & Compliance zone"],
    processing: "Provides controls for: per-tier retention periods, immediate tier deletion (triggers crypto-shredding), data export (GDPR Art. 20), right to erasure (GDPR Art. 17), and recording indicator preferences. All changes are signed and sent to the device over BLE.",
  },
  ota: {
    title: "OTA Firmware Update",
    explanation: "Secure over-the-air firmware updates delivered from the cloud. The device pulls new firmware from Supabase Storage and verifies it with Ed25519 signatures before flashing.",
    inputs: ["Signed firmware image from Supabase Storage"],
    outputs: ["Updated firmware flashed to ESP32"],
    processing: "The companion app notifies the wearer of available updates. On approval, the device downloads the firmware image over WiFi from Supabase Storage. The image is Ed25519-signed — the device verifies the signature against a pinned public key before flashing. Supports rollback to the previous version if boot fails.",
  },
  consent: {
    title: "Consent Settings",
    explanation: "Granular consent management in the companion app — the wearer explicitly opts in or out of specific data processing types.",
    inputs: ["User consent choices from the companion app UI"],
    outputs: ["Consent flags to device and cloud pipelines"],
    processing: "Manages per-category consent: audio capture, environmental analysis, emotional analysis. Consent state is cryptographically signed and stored both on-device and in Supabase. Changes take effect immediately.",
  },
  /* ── Privacy & Compliance ── */
  crypto: {
    title: "Crypto-Shredding",
    explanation: "The nuclear option for privacy. Each tier's data is encrypted with its own key stored in the ESP32's eFuse-protected block. Deleting the key makes all that tier's data permanently unrecoverable — without touching the flash.",
    inputs: ["Deletion command from Companion App via cloud"],
    outputs: ["Tier data rendered cryptographically unrecoverable"],
    processing: "Each tier is encrypted with a per-tier AES-256-GCM key. On deletion request: Supabase deletes cloud-side data via cascading delete, then sends wipe command to device. Device deletes the tier's encryption key from eFuse-protected storage. Signs a DeletionAttestation that the app can verify.",
  },
  pot: {
    title: "Potentiometer",
    explanation: "A physical dial on the device that lets the wearer scroll through consultation results and adjust E-Ink display contrast.",
    inputs: ["Analog voltage from wearer turning the dial"],
    outputs: ["Scroll zone / contrast level to E-Ink display controller"],
    processing: "Connected to GPIO 8 (ADC). The ESP32 reads the analog value, maps it to 5 scroll zones or a contrast range, and updates the E-Ink display accordingly. No cloud involvement — purely local hardware control.",
  },
  haptic: {
    title: "Haptic Motor (DRV2605L)",
    explanation: "A small vibration motor that provides tactile feedback — a short buzz when the button is pressed and a distinct pattern when a consultation response arrives on the E-Ink display.",
    inputs: ["Button press event from GPIO ISR", "Response-ready signal from Rule Constraint Layer"],
    outputs: ["Vibration pattern felt by the wearer"],
    processing: "Driven by a DRV2605L haptic driver over I2C. Two patterns: a quick 50ms tap on button press (confirmation), and a double-pulse pattern when a consultation response is rendered on E-Ink. Draws up to 80mA peak during vibration.",
  },
  wifi: {
    title: "WiFi Credentials",
    explanation: "The stored WiFi credentials that allow the device to connect to the internet for Supabase communication. Written once during provisioning and encrypted at rest.",
    inputs: ["Encrypted credentials from BLE provisioning flow"],
    outputs: ["WiFi connection parameters to the ESP32 WiFi stack"],
    processing: "Stored in the ESP32's encrypted NVS partition (AES-XTS with eFuse-bound key). On boot, the WiFi stack reads credentials from NVS to establish a TLS connection to Supabase.",
  },
  nvs: {
    title: "NVS Encrypted Storage",
    explanation: "The ESP32's encrypted Non-Volatile Storage partition that holds WiFi credentials and per-tier encryption keys. Protected by an eFuse-bound AES-XTS key that cannot be read by software.",
    inputs: ["WiFi credentials from provisioning flow", "Per-tier encryption keys generated at setup"],
    outputs: ["Credentials to WiFi stack on boot", "Tier keys to crypto-shredding module on deletion"],
    processing: "Uses the ESP32's hardware-encrypted NVS partition. The AES-XTS encryption key is stored in eFuse block 1 and is only accessible by the flash encryption hardware — not readable by any software, including firmware. This is the root of trust for all on-device encryption.",
  },
  erasure: {
    title: "Right to Erasure (GDPR Art. 17)",
    explanation: "Implements the GDPR right to erasure — the wearer can request complete deletion of all their data. This triggers crypto-shredding of all tier keys and cascading deletes in Supabase.",
    inputs: ["Erasure request from Privacy Controls in companion app"],
    outputs: ["Crypto-shredding command to destroy all tier encryption keys", "Cascading delete in Supabase Postgres"],
    processing: "On erasure request: (1) Supabase deletes all server-side data (cascading delete on device_id), (2) device triggers crypto-shredding for all tiers, (3) device signs a DeletionAttestation proving the data was destroyed, (4) companion app receives and displays the attestation. Irreversible.",
  },
  dataexp: {
    title: "Data Export (GDPR Art. 20)",
    explanation: "Implements GDPR data portability — the wearer can export all their data in a machine-readable format. Exports long-term themes and tier summaries as JSON + a human-readable PDF.",
    inputs: ["Export request from Privacy Controls", "Theme data from Tier 4 in Postgres"],
    outputs: ["JSON + PDF export package to companion app"],
    processing: "On export request: reads all tier summaries and Tier 4 themes from Supabase Postgres, packages them as structured JSON (machine-readable) and a formatted PDF (human-readable). The export includes: all theme patterns, emotional history, topic history, and consultation history. Delivered to the companion app for download.",
  },
  recindicator: {
    title: "Recording Indicator",
    explanation: "A hardwired LED that is physically connected to the microphone power line — it is impossible to record audio without the LED being lit. This is a privacy-critical hardware guarantee, not a software feature.",
    inputs: ["Microphone power state (hardwired electrical connection)"],
    outputs: ["Visible LED indicator to people around the wearer"],
    processing: "The LED is wired in series with the INMP441 microphone's power supply. When the mic draws current, the LED lights up. There is no software control — this is a hardware guarantee that recording cannot happen invisibly. Complies with two-party consent recording laws.",
  },
};
